name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            Merhaba,
            Bu konunun son zamanlarda herhangi bir etkinlik içermediğini ve yakında otomatik olarak kapatılabileceğini size  hatırlatmak istedik, ancak gerektiğinde bu konuyu yeniden açabilirsiniz. 
            Proje ile ilgili farklı soru ve önerileriniz için yeni konular(issue) oluşturabilirsiniz. 
            Digital Eye Mammography projesine ve sağlıkta yapay zekâ çalışmalarına katkılarınız için teşekkür ederiz.
          
          stale-pr-message: 'Bu çekme isteği uzun süredir güncellenmedi ve yakında kapatılabilir.'
          days-before-issue-stale: 30
          days-before-issue-close: 10
          days-before-pr-stale: 90
          days-before-pr-close: 30
          stale-issue-label: 'stale'
          close-issue-label: 'closed'
          operations-per-run: 300
